// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
public class SeleniumTestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void seleniumTest() {
        driver.get("https://www.google.co.kr/");
        driver.manage().window().setSize(new Dimension(1280, 905));
        driver.findElement(By.linkText("Google 정보")).click();
        driver.findElement(By.linkText("제품")).click();
        driver.findElement(By.linkText("약속")).click();
        driver.close();
    }
}
